#!/usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use Acme\DatabaseAdapter;

require 'vendor/autoload.php';

$app = new Application('Odot', '1.0');

try {
  $pdo = new PDO('sqlite:db');
  $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (Exception $e) {
  echo $e->getMessage();
  exit(1);
}

$dbAdapter = new DatabaseAdapter($pdo);

$app->add(new Acme\ShowCommand($dbAdapter));
$app->add(new Acme\AddCommand($dbAdapter));
$app->add(new Acme\CompleteCommand($dbAdapter));

$app->run();
